### ISSUE TITLE
Loader stuck at this <instaloader.nodeiterator.NodeIterator object at 0x7fe1476b7ba8>

### ISSUE THREAD

**Issue by Siddhartha2610** [nathan-149/automated_youtube_channel#9]
Code is not moving forward from this point. I can see the loader object has created but nothing is working while credentials are correct and set up properly.  

Could you please help me to resolve this issue or at least point me in the right direction if I'm missing something here?

**Comment by vinay6402** [comment]
resolved?

**Comment by kwamzdee** [comment]
not yet resolved for me, please help. Getting the same error as shared here

**Comment by Real-Edgy** [comment]
same issue here - looks to be related to the user-agent? Anyone solve this? 

Traceback (most recent call last):
  File "botTuber.py", line 335, in <module>
    attemptRoutine()
  File "botTuber.py", line 326, in attemptRoutine
    routine(title, description, tags)
  File "botTuber.py", line 151, in routine
    scrapeVideos(username = IG_USERNAME,
  File "/home/user/youtube/scrape_videos.py", line 57, in scrapeVideos
    scrape_videos_fn()
  File "/home/user/youtube/scrape_videos.py", line 32, in scrape_videos_fn
    looter = ProfileLooter(acc, videos_only=True, dump_json=True, template="{id}-{username}-{width}-{height}")
  File "/usr/local/lib/python3.8/dist-packages/instalooter/looters.py", line 705, in __init__
    super(ProfileLooter, self).__init__(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/instalooter/looters.py", line 283, in __init__
    self.session.headers['User-Agent'] = self._user_agent
  File "/usr/local/lib/python3.8/dist-packages/instalooter/_utils.py", line 85, in __get__
    self.value = self.factory.__get__(obj, klass)()
  File "/usr/local/lib/python3.8/dist-packages/instalooter/looters.py", line 71, in _user_agent
    ua = get_user_agent(cache=cls._cachefs.getsyspath(cls._USERAGENT_FILE))
  File "/usr/local/lib/python3.8/dist-packages/instalooter/_uadetect.py", line 58, in get_user_agent
    user_agent = UserAgentRequestHandler.queue.get()
  File "/usr/lib/python3.8/queue.py", line 170, in get
    self.not_empty.wait()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
